### ISSUE TITLE
Ability to delete NPCs and/or Spells

### ISSUE THREAD

**Issue by FantasyModuleParser** [FantasyModuleParser/FantasyModuleParser#38]
Users have stated that they would love the ability to delete a NPC or Spell after it has been created. This allows unintentional NPCs/Spells from making it into the wrong modules.

From discussion with @fredska, it seems that a way to remove the NPC or Spell from ModuleModel memory is required before Add to Project is pressed by end user.

**Comment by fredska** [comment]
Closing this issue, as the pull request #76 adds a Category Management option to allow the removal of existing NPCs, Spells, Tables, Equipment and Classes
