### ISSUE TITLE
Error in Parsing Tables

### ISSUE THREAD

**Issue by FantasyModuleParser** [FantasyModuleParser/FantasyModuleParser#67]
![unknown](https://user-images.githubusercontent.com/76872275/140411683-ab2e59d7-8ea3-4afc-a06a-a2df7bf21dad.png)

**Reported by:** ghen
**FMP Version:** 0.2.3.2
**OS Version:** Win10 20H2
**FMP Section:** Tables
**Detailed Steps:** After creating a table successfully, saving it, adding it to my module, and then hitting "new table" the headers from the first table were still there. When trying to change the headers or perform other edits to the new table these problems would happen, but only on the 5th, and 6th columns in a 6 column table.

**Further Testing:** closing and reopening FMP without loading the other table first fixes the issue. If I open the 1st table after reopening FMP and make a new table again the bug reoccurs. So my theory is in cleaning out the memory on 'New Table'

[Random_Hometown.zip](https://github.com/FantasyModuleParser/FantasyModuleParser/files/7478161/Random_Hometown.zip)

**Comment by FantasyModuleParser** [comment]
In version 0.2.3.4, I recreated the table manually and saved it. Upon hitting New Table, the Column Headers definitely persist from the previous table.

Upon trying to change the headers, I got the same error as *ghen* when I tried to edit the 4th column (in Example, Themes)

**Comment by fredska** [comment]
With the merging of #76, this issue should be resolved as the Table module was re-worked to maintain column header information in a way that should be more reliable
